# Generated by Django 5.2.17 on 2026-08-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='energy_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='tag',
            field=models.CharField(max_length=100),
        ),
    ]
